### ISSUE TITLE
Pre-Moveover Checklist

### ISSUE THREAD

**Issue by RyanSquared** [hashbang/k8s-irc#3]
- [x] Upgrade Oragono to the 2.0.0 release
- [x] Import remaining operator blocks
- [ ] Get a valid TLS certificate
  - Ideally using jetstack/cert-manager(?), so we don't have to manually renew
- [ ] Register the highest-value channels to some trusted account (#!, #!social, #!opers which should be +i)
- [ ] Cut over DNS

**Comment by slingamn** [comment]
Let's also:

- [ ] do a failover drill with `/debug crashserver` (deliberately crashes the server, verifying that k8s recovers correctly)

**Comment by slingamn** [comment]
I can import the remaining operator blocks if you remind me where your existing configs are (can't find the link in my logs).

re. upgrading Oragono:

https://github.com/hashbang/k8s-irc/blob/3580a1290d64ee1c81ba54ececc0b75751d541b1/base/resources.yml#L21

I don't know where this image is pulled from, or how it's stored --- I think @daurnimator rebuilt it locally? To run the stable release 2.0.0, you can pull from [dockerhub](https://hub.docker.com/r/oragono/oragono/tags), apparently it's `docker pull oragono/oragono:latest`.

**Comment by slingamn** [comment]
@RyanSquared @daurnimator next week?
